/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;

const appRouter = t.router({
  auth: t.router({
    register: publicProcedure
      .input(z.object({
      name: z.string().min(2).max(80),
      username: z.string().min(3).max(32),
      password: z.string().min(8).max(128),
    }))
      .output(z.object({
      user: z.object({ id: z.string(), name: z.string(), username: z.string() }),
      accessToken: z.string(),
      refreshToken: z.string(),
    }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    login: publicProcedure
      .input(z.object({ username: z.string().min(3).max(32), password: z.string().min(8).max(128) }))
      .output(z.object({
      user: z.object({ id: z.string(), name: z.string(), username: z.string() }),
      accessToken: z.string(),
      refreshToken: z.string(),
    }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    refresh: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1) }))
      .output(z.object({
      user: z.object({ id: z.string(), name: z.string(), username: z.string() }),
      accessToken: z.string(),
      refreshToken: z.string(),
    }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    logout: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1) }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    me: publicProcedure
      .output(z.object({ id: z.string(), name: z.string(), username: z.string() }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
