/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;

const appRouter = t.router({
  auth: t.router({
    register: publicProcedure
      .input(z.object({
      name: z.string().min(2).max(80),
      username: z.string().min(3).max(32),
      password: z.string().min(8).max(128),
    }))
      .output(z.object({ user: z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}), accessToken: z.string(), refreshToken: z.string() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    login: publicProcedure
      .input(z.object({ username: z.string().min(3).max(32), password: z.string().min(8).max(128) }))
      .output(z.object({ user: z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}), accessToken: z.string(), refreshToken: z.string() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    refresh: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1) }))
      .output(z.object({ user: z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}), accessToken: z.string(), refreshToken: z.string() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    logout: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1) }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    park: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1) }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    pinLogin: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1), pin: z.string().regex(/^\d{6}$/, 'PIN must be 6 digits.') }))
      .output(z.object({ user: z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}), accessToken: z.string(), refreshToken: z.string() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    setPin: publicProcedure
      .input(z.object({ pin: z.string().regex(/^\d{6}$/, 'PIN must be 6 digits.'), password: z.string().min(8).max(128).optional() }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    me: publicProcedure
      .output(z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}).extend({ permissions: z.array(z.string()) }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  reservation: t.router({
    list: publicProcedure
      .input(z.object({ from: z.iso.datetime({ offset: true }), to: z.iso.datetime({ offset: true }) }))
      .output(z.array(z.object({
  id: z.string(),
  tableId: z.string(),
  customerName: z.string(),
  phone: z.string().nullable(),
  partySize: z.number(),
  startsAt: z.string(),
  note: z.string().nullable(),
  status: z.enum(['booked', 'seated', 'cancelled', 'no_show']),
})))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      tableId: z.string(),
      customerName: z.string().trim().min(1).max(80),
      phone: z.string().trim().max(32).optional(),
      partySize: z.number().int().min(1).max(100),
      startsAt: z.iso.datetime({ offset: true }),
      note: z.string().trim().max(500).optional(),
    }))
      .output(z.object({
  id: z.string(),
  tableId: z.string(),
  customerName: z.string(),
  phone: z.string().nullable(),
  partySize: z.number(),
  startsAt: z.string(),
  note: z.string().nullable(),
  status: z.enum(['booked', 'seated', 'cancelled', 'no_show']),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      id: z.string(),
      status: z.enum(['seated', 'cancelled', 'no_show']).optional(),
      tableId: z.string().optional(),
      customerName: z.string().trim().min(1).max(80).optional(),
      phone: z.string().trim().max(32).optional(),
      partySize: z.number().int().min(1).max(100).optional(),
      startsAt: z.iso.datetime({ offset: true }).optional(),
      note: z.string().trim().max(500).optional(),
    }))
      .output(z.object({
  id: z.string(),
  tableId: z.string(),
  customerName: z.string(),
  phone: z.string().nullable(),
  partySize: z.number(),
  startsAt: z.string(),
  note: z.string().nullable(),
  status: z.enum(['booked', 'seated', 'cancelled', 'no_show']),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  table: t.router({
    list: publicProcedure
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
})))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      name: z.string().trim().min(1).max(20),
      seats: z.number().int().min(1).max(50),
      x: z.number().int().min(0).max(1000),
      y: z.number().int().min(0).max(1000),
      w: z.number().int().min(40).max(500),
      h: z.number().int().min(40).max(500),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      id: z.string(),
      name: z.string().trim().min(1).max(20),
      seats: z.number().int().min(1).max(50),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    updateLayout: publicProcedure
      .input(z.object({ items: z.array(z.object({
  id: z.string(),
  x: z.number().int().min(0).max(1000),
  y: z.number().int().min(0).max(1000),
  w: z.number().int().min(40).max(500),
  h: z.number().int().min(40).max(500),
})).min(1).max(200) }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
})))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure
      .input(z.object({ id: z.string() }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    merge: publicProcedure
      .input(z.object({ headId: z.string(), memberIds: z.array(z.string()).min(1).max(50) }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
})))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    unmerge: publicProcedure
      .input(z.object({ id: z.string() }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
})))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  settings: t.router({
    get: publicProcedure
      .output(z.object({ idleTimeoutSeconds: z.number() }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({ idleTimeoutSeconds: z.number().int().min(30).max(3600) }))
      .output(z.object({ idleTimeoutSeconds: z.number() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
