/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;

const appRouter = t.router({
  addon: t.router({
    list: publicProcedure
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  minSelect: z.number().int(),
  maxSelect: z.number().int(),
  options: z.array(
    z.object({ id: z.string(), name: z.string(), price: z.number().int(), available: z.boolean() }),
  ),
  usedBy: z.number().int(),
})))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      name: z.string().trim().min(1).max(60),
      minSelect: z.number().int().min(0).max(50),
      maxSelect: z.number().int().min(1).max(50),
      options: z
        .array(
          z.object({
            id: z.uuid().optional(),
            name: z.string().trim().min(1).max(60),
            price: z.number().int().min(0).max(100000000),
            available: z.boolean(),
          }),
        )
        .min(1)
        .max(50),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  minSelect: z.number().int(),
  maxSelect: z.number().int(),
  options: z.array(
    z.object({ id: z.string(), name: z.string(), price: z.number().int(), available: z.boolean() }),
  ),
  usedBy: z.number().int(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      id: z.uuid(),
      name: z.string().trim().min(1).max(60),
      minSelect: z.number().int().min(0).max(50),
      maxSelect: z.number().int().min(1).max(50),
      options: z
        .array(
          z.object({
            id: z.uuid().optional(),
            name: z.string().trim().min(1).max(60),
            price: z.number().int().min(0).max(100000000),
            available: z.boolean(),
          }),
        )
        .min(1)
        .max(50),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  minSelect: z.number().int(),
  maxSelect: z.number().int(),
  options: z.array(
    z.object({ id: z.string(), name: z.string(), price: z.number().int(), available: z.boolean() }),
  ),
  usedBy: z.number().int(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure
      .input(z.object({ id: z.uuid() }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  audit: t.router({
    list: publicProcedure
      .input(z.object({
      outletId: z.uuid(),
      fromDate: z.iso.date(),
      toDate: z.iso.date(),
      module: z
        .enum(['settings', 'outlet', 'staff', 'category', 'menu', 'addon', 'role', 'approval'])
        .optional(),
      userId: z.uuid().optional(),
      cursor: z.object({ createdAt: z.string().max(40), id: z.uuid() }).optional(),
    }))
      .output(z.object({
      rows: z.array(z.object({
  id: z.string(),
  createdAt: z.string(),
  module: z.enum(['settings', 'outlet', 'staff', 'category', 'menu', 'addon', 'role', 'approval']),
  action: z.string(),
  entityType: z.string(),
  entityId: z.string().nullable(),
  reason: z.string().nullable(),
  before: z.record(z.string(), z.unknown()).nullable(),
  after: z.record(z.string(), z.unknown()).nullable(),
  actorName: z.string(),
  approverName: z.string().nullable(),
})),
      nextCursor: z.object({ createdAt: z.string(), id: z.string() }).nullable(),
    }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    actors: publicProcedure
      .input(z.object({ outletId: z.uuid() }))
      .output(z.array(z.object({ id: z.string(), name: z.string() })))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  approval: t.router({
    approvers: publicProcedure
      .input(z.object({ permission: z.string().max(60) }))
      .output(z.array(z.object({ id: z.string(), name: z.string() })))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    unblock: publicProcedure
      .input(z.object({ userId: z.uuid() }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  auth: t.router({
    login: publicProcedure
      .input(z.object({ username: z.string().min(3).max(32), password: z.string().min(8).max(128) }))
      .output(z.object({
  user: z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}),
  accessToken: z.string(),
  refreshToken: z.string(),
  outlet: z.object({ id: z.string(), name: z.string() }).nullable(),
  outlets: z.array(z.object({ id: z.string(), name: z.string() })),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    refresh: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1), outletId: z.uuid().optional() }))
      .output(z.object({
  user: z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}),
  accessToken: z.string(),
  refreshToken: z.string(),
  outlet: z.object({ id: z.string(), name: z.string() }).nullable(),
  outlets: z.array(z.object({ id: z.string(), name: z.string() })),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    logout: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1) }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    park: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1) }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    pinLogin: publicProcedure
      .input(z.object({ refreshToken: z.string().min(1), pin: z.string().regex(/^\d{6}$/, 'PIN must be 6 digits.') }))
      .output(z.object({
  user: z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}),
  accessToken: z.string(),
  refreshToken: z.string(),
  outlet: z.object({ id: z.string(), name: z.string() }).nullable(),
  outlets: z.array(z.object({ id: z.string(), name: z.string() })),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    setPin: publicProcedure
      .input(z.object({ pin: z.string().regex(/^\d{6}$/, 'PIN must be 6 digits.'), password: z.string().min(8).max(128).optional() }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    me: publicProcedure
      .output(z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  hasPin: z.boolean(),
}).extend({ outletId: z.string().nullable(), permissions: z.array(z.string()) }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  category: t.router({
    list: publicProcedure
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  sortOrder: z.number().int(),
  color: z.string().nullable(),
  active: z.boolean(),
  kitchenStationId: z.string().nullable(),
  // Live menu items in the category.
  itemCount: z.number().int(),
})))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      name: z.string().trim().min(1).max(40),
      color: z
        .string()
        .regex(/^#[0-9a-fA-F]{6}$/)
        .nullable()
        .optional(),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  sortOrder: z.number().int(),
  color: z.string().nullable(),
  active: z.boolean(),
  kitchenStationId: z.string().nullable(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      id: z.uuid(),
      name: z.string().trim().min(1).max(40),
      color: z
        .string()
        .regex(/^#[0-9a-fA-F]{6}$/)
        .nullable(),
      active: z.boolean(),
      kitchenStationId: z.uuid().nullable(),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  sortOrder: z.number().int(),
  color: z.string().nullable(),
  active: z.boolean(),
  kitchenStationId: z.string().nullable(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure
      .input(z.object({ id: z.uuid() }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    reorder: publicProcedure
      .input(z.object({ ids: z.array(z.uuid()).max(200) }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  sortOrder: z.number().int(),
  color: z.string().nullable(),
  active: z.boolean(),
  kitchenStationId: z.string().nullable(),
})))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  reservation: t.router({
    list: publicProcedure
      .input(z.object({ from: z.iso.datetime({ offset: true }), to: z.iso.datetime({ offset: true }) }))
      .output(z.array(z.object({
  id: z.string(),
  tableId: z.string(),
  customerName: z.string(),
  phone: z.string().nullable(),
  partySize: z.number(),
  startsAt: z.string(),
  note: z.string().nullable(),
  status: z.enum(['booked', 'seated', 'cancelled', 'no_show']),
})))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      tableId: z.string(),
      customerName: z.string().trim().min(1).max(80),
      phone: z.string().trim().max(32).optional(),
      partySize: z.number().int().min(1).max(100),
      startsAt: z.iso.datetime({ offset: true }),
      note: z.string().trim().max(500).optional(),
      approval: z
        .object({
          approverUserId: z.uuid(),
          pin: z.string().regex(/^\d{6}$/),
          reason: z.string().trim().max(200).optional(),
        })
        .optional(),
    }))
      .output(z.object({
  id: z.string(),
  tableId: z.string(),
  customerName: z.string(),
  phone: z.string().nullable(),
  partySize: z.number(),
  startsAt: z.string(),
  note: z.string().nullable(),
  status: z.enum(['booked', 'seated', 'cancelled', 'no_show']),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      id: z.string(),
      status: z.enum(['seated', 'cancelled', 'no_show']).optional(),
      tableId: z.string().optional(),
      customerName: z.string().trim().min(1).max(80).optional(),
      phone: z.string().trim().max(32).optional(),
      partySize: z.number().int().min(1).max(100).optional(),
      startsAt: z.iso.datetime({ offset: true }).optional(),
      note: z.string().trim().max(500).optional(),
      approval: z
        .object({
          approverUserId: z.uuid(),
          pin: z.string().regex(/^\d{6}$/),
          reason: z.string().trim().max(200).optional(),
        })
        .optional(),
    }))
      .output(z.object({
  id: z.string(),
  tableId: z.string(),
  customerName: z.string(),
  phone: z.string().nullable(),
  partySize: z.number(),
  startsAt: z.string(),
  note: z.string().nullable(),
  status: z.enum(['booked', 'seated', 'cancelled', 'no_show']),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  table: t.router({
    list: publicProcedure
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
})))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      name: z.string().trim().min(1).max(20),
      seats: z.number().int().min(1).max(50),
      x: z.number().int().min(0).max(1000),
      y: z.number().int().min(0).max(1000),
      w: z.number().int().min(40).max(500),
      h: z.number().int().min(40).max(500),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      id: z.string(),
      name: z.string().trim().min(1).max(20),
      seats: z.number().int().min(1).max(50),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    updateLayout: publicProcedure
      .input(z.object({ items: z.array(z.object({
  id: z.string(),
  x: z.number().int().min(0).max(1000),
  y: z.number().int().min(0).max(1000),
  w: z.number().int().min(40).max(500),
  h: z.number().int().min(40).max(500),
})).min(1).max(200) }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
})))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure
      .input(z.object({ id: z.string() }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    merge: publicProcedure
      .input(z.object({
      headId: z.string(),
      memberIds: z.array(z.string()).min(1).max(50),
      approval: z
        .object({
          approverUserId: z.uuid(),
          pin: z.string().regex(/^\d{6}$/),
          reason: z.string().trim().max(200).optional(),
        })
        .optional(),
    }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
})))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    unmerge: publicProcedure
      .input(z.object({
      id: z.string(),
      approval: z
        .object({
          approverUserId: z.uuid(),
          pin: z.string().regex(/^\d{6}$/),
          reason: z.string().trim().max(200).optional(),
        })
        .optional(),
    }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  seats: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  mergedIntoId: z.string().nullable(),
})))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  menu: t.router({
    list: publicProcedure
      .output(z.object({
      categories: z.array(
        z.object({
          id: z.string(),
          name: z.string(),
          sortOrder: z.number().int(),
          color: z.string().nullable(),
          active: z.boolean(),
          kitchenStationId: z.string().nullable(),
          itemCount: z.number().int(),
        }),
      ),
      items: z.array(z.object({
  id: z.string(),
  categoryId: z.string(),
  categoryName: z.string(),
  code: z.string().nullable(),
  name: z.string(),
  kitchenName: z.string().nullable(),
  description: z.string().nullable(),
  imageUrl: z.string().nullable(),
  // With variants: the lowest variant price, for display only.
  price: z.number().int(),
  // Null when not entered, when the item has variants - and always null for a caller without `menu.manage`.
  cost: z.number().int().nullable(),
  tax: z.enum(['pbjt', 'ppn', 'none']),
  // The item's own station (null: inherits) and the resolved one a line would route to.
  kitchenStationId: z.string().nullable(),
  stationId: z.string().nullable(),
  soldBy: z.enum(['unit', 'weight']),
  sortOrder: z.number().int(),
  active: z.boolean(),
  variants: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
      price: z.number().int(),
      cost: z.number().int().nullable(),
      available: z.boolean(),
    }),
  ),
  addonGroupIds: z.array(z.string()),
})),
      addonGroups: z.array(
        z.object({
          id: z.string(),
          name: z.string(),
          minSelect: z.number().int(),
          maxSelect: z.number().int(),
          options: z.array(
            z.object({ id: z.string(), name: z.string(), price: z.number().int(), available: z.boolean() }),
          ),
          usedBy: z.number().int(),
        }),
      ),
    }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    taxRates: publicProcedure
      .output(z.object({ pbjtRateBp: z.number().int(), ppnRateBp: z.number().int() }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      categoryId: z.uuid(),
      code: z
        .string()
        .trim()
        .max(20)
        .regex(/^[A-Za-z0-9-]*$/)
        .nullable(),
      name: z.string().trim().min(1).max(60),
      kitchenName: z.string().trim().min(1).max(60).nullable(),
      description: z.string().trim().min(1).max(500).nullable(),
      imageUrl: z
        .url({ protocol: /^https?$/ })
        .max(500)
        .nullable(),
      price: z.number().int().min(0).max(100000000),
      cost: z.number().int().min(0).max(100000000).nullable(),
      tax: z.enum(['pbjt', 'ppn', 'none']),
      kitchenStationId: z.uuid().nullable(),
      soldBy: z.enum(['unit', 'weight']),
      active: z.boolean(),
      variants: z
        .array(
          z.object({
            id: z.uuid().optional(),
            name: z.string().trim().min(1).max(60),
            price: z.number().int().min(0).max(100000000),
            cost: z.number().int().min(0).max(100000000).nullable(),
            available: z.boolean(),
          }),
        )
        .max(30),
      addonGroupIds: z.array(z.uuid()).max(20),
    }))
      .output(z.object({
  id: z.string(),
  categoryId: z.string(),
  categoryName: z.string(),
  code: z.string().nullable(),
  name: z.string(),
  kitchenName: z.string().nullable(),
  description: z.string().nullable(),
  imageUrl: z.string().nullable(),
  // With variants: the lowest variant price, for display only.
  price: z.number().int(),
  // Null when not entered, when the item has variants - and always null for a caller without `menu.manage`.
  cost: z.number().int().nullable(),
  tax: z.enum(['pbjt', 'ppn', 'none']),
  // The item's own station (null: inherits) and the resolved one a line would route to.
  kitchenStationId: z.string().nullable(),
  stationId: z.string().nullable(),
  soldBy: z.enum(['unit', 'weight']),
  sortOrder: z.number().int(),
  active: z.boolean(),
  variants: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
      price: z.number().int(),
      cost: z.number().int().nullable(),
      available: z.boolean(),
    }),
  ),
  addonGroupIds: z.array(z.string()),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      id: z.uuid(),
      categoryId: z.uuid(),
      code: z
        .string()
        .trim()
        .max(20)
        .regex(/^[A-Za-z0-9-]*$/)
        .nullable(),
      name: z.string().trim().min(1).max(60),
      kitchenName: z.string().trim().min(1).max(60).nullable(),
      description: z.string().trim().min(1).max(500).nullable(),
      imageUrl: z
        .url({ protocol: /^https?$/ })
        .max(500)
        .nullable(),
      price: z.number().int().min(0).max(100000000),
      cost: z.number().int().min(0).max(100000000).nullable(),
      tax: z.enum(['pbjt', 'ppn', 'none']),
      kitchenStationId: z.uuid().nullable(),
      soldBy: z.enum(['unit', 'weight']),
      active: z.boolean(),
      variants: z
        .array(
          z.object({
            id: z.uuid().optional(),
            name: z.string().trim().min(1).max(60),
            price: z.number().int().min(0).max(100000000),
            cost: z.number().int().min(0).max(100000000).nullable(),
            available: z.boolean(),
          }),
        )
        .max(30),
      addonGroupIds: z.array(z.uuid()).max(20),
    }))
      .output(z.object({
  id: z.string(),
  categoryId: z.string(),
  categoryName: z.string(),
  code: z.string().nullable(),
  name: z.string(),
  kitchenName: z.string().nullable(),
  description: z.string().nullable(),
  imageUrl: z.string().nullable(),
  // With variants: the lowest variant price, for display only.
  price: z.number().int(),
  // Null when not entered, when the item has variants - and always null for a caller without `menu.manage`.
  cost: z.number().int().nullable(),
  tax: z.enum(['pbjt', 'ppn', 'none']),
  // The item's own station (null: inherits) and the resolved one a line would route to.
  kitchenStationId: z.string().nullable(),
  stationId: z.string().nullable(),
  soldBy: z.enum(['unit', 'weight']),
  sortOrder: z.number().int(),
  active: z.boolean(),
  variants: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
      price: z.number().int(),
      cost: z.number().int().nullable(),
      available: z.boolean(),
    }),
  ),
  addonGroupIds: z.array(z.string()),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    setActive: publicProcedure
      .input(z.object({ id: z.uuid(), active: z.boolean() }))
      .output(z.object({ id: z.string(), active: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure
      .input(z.object({ id: z.uuid() }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  outlet: t.router({
    list: publicProcedure
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.enum(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
  pbjtLabel: z.string(),
  pbjtRateBp: z.number().int(),
  pbjtInclusive: z.boolean(),
  serviceName: z.string(),
  serviceRateBp: z.number().int(),
  servicePbjtTaxable: z.boolean(),
  serviceOrderTypes: z.array(z.enum(['dine_in', 'takeaway', 'delivery'])),
  npwp: z.string().nullable(),
  npwpd: z.string().nullable(),
  ppnInclusive: z.boolean(),
  ppnRateBp: z.number().int(),
  businessDayCutoff: z.string(),
  businessDayAutoClose: z.string().nullable(),
  active: z.boolean(),
})))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    get: publicProcedure
      .input(z.object({ id: z.uuid() }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.enum(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
  pbjtLabel: z.string(),
  pbjtRateBp: z.number().int(),
  pbjtInclusive: z.boolean(),
  serviceName: z.string(),
  serviceRateBp: z.number().int(),
  servicePbjtTaxable: z.boolean(),
  serviceOrderTypes: z.array(z.enum(['dine_in', 'takeaway', 'delivery'])),
  npwp: z.string().nullable(),
  npwpd: z.string().nullable(),
  ppnInclusive: z.boolean(),
  ppnRateBp: z.number().int(),
  businessDayCutoff: z.string(),
  businessDayAutoClose: z.string().nullable(),
  active: z.boolean(),
}))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      name: z.string().trim().min(1).max(60),
      code: z
        .string()
        .trim()
        .min(1)
        .max(12)
        .regex(/^[a-zA-Z0-9-]+$/),
      address: z.string().trim().max(200).optional(),
      phone: z.string().trim().max(32).optional(),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.enum(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
  pbjtLabel: z.string(),
  pbjtRateBp: z.number().int(),
  pbjtInclusive: z.boolean(),
  serviceName: z.string(),
  serviceRateBp: z.number().int(),
  servicePbjtTaxable: z.boolean(),
  serviceOrderTypes: z.array(z.enum(['dine_in', 'takeaway', 'delivery'])),
  npwp: z.string().nullable(),
  npwpd: z.string().nullable(),
  ppnInclusive: z.boolean(),
  ppnRateBp: z.number().int(),
  businessDayCutoff: z.string(),
  businessDayAutoClose: z.string().nullable(),
  active: z.boolean(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      id: z.uuid(),
      name: z.string().trim().min(1).max(60),
      address: z.string().trim().max(200).optional(),
      phone: z.string().trim().max(32).optional(),
      city: z.string().trim().max(60).optional(),
      timezone: z.enum(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.enum(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
  pbjtLabel: z.string(),
  pbjtRateBp: z.number().int(),
  pbjtInclusive: z.boolean(),
  serviceName: z.string(),
  serviceRateBp: z.number().int(),
  servicePbjtTaxable: z.boolean(),
  serviceOrderTypes: z.array(z.enum(['dine_in', 'takeaway', 'delivery'])),
  npwp: z.string().nullable(),
  npwpd: z.string().nullable(),
  ppnInclusive: z.boolean(),
  ppnRateBp: z.number().int(),
  businessDayCutoff: z.string(),
  businessDayAutoClose: z.string().nullable(),
  active: z.boolean(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    setCode: publicProcedure
      .input(z.object({
      id: z.uuid(),
      code: z
        .string()
        .trim()
        .min(1)
        .max(12)
        .regex(/^[a-zA-Z0-9-]+$/),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.enum(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
  pbjtLabel: z.string(),
  pbjtRateBp: z.number().int(),
  pbjtInclusive: z.boolean(),
  serviceName: z.string(),
  serviceRateBp: z.number().int(),
  servicePbjtTaxable: z.boolean(),
  serviceOrderTypes: z.array(z.enum(['dine_in', 'takeaway', 'delivery'])),
  npwp: z.string().nullable(),
  npwpd: z.string().nullable(),
  ppnInclusive: z.boolean(),
  ppnRateBp: z.number().int(),
  businessDayCutoff: z.string(),
  businessDayAutoClose: z.string().nullable(),
  active: z.boolean(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    setCharges: publicProcedure
      .input(z.object({
      id: z.uuid(),
      pbjtLabel: z.string().trim().min(1).max(30),
      pbjtRateBp: z.number().int().min(0).max(10000),
      pbjtInclusive: z.boolean(),
      serviceName: z.string().trim().min(1).max(30),
      serviceRateBp: z.number().int().min(0).max(10000),
      servicePbjtTaxable: z.boolean(),
      serviceOrderTypes: z.array(z.enum(['dine_in', 'takeaway', 'delivery'])).max(3),
      // Digits only — the client strips the dots and dash of the printed form.
      npwp: z
        .string()
        .regex(/^\d{15,16}$/)
        .optional(),
      npwpd: z.string().trim().max(30).optional(),
      ppnInclusive: z.boolean(),
      ppnRateBp: z.number().int().min(0).max(10000),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.enum(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
  pbjtLabel: z.string(),
  pbjtRateBp: z.number().int(),
  pbjtInclusive: z.boolean(),
  serviceName: z.string(),
  serviceRateBp: z.number().int(),
  servicePbjtTaxable: z.boolean(),
  serviceOrderTypes: z.array(z.enum(['dine_in', 'takeaway', 'delivery'])),
  npwp: z.string().nullable(),
  npwpd: z.string().nullable(),
  ppnInclusive: z.boolean(),
  ppnRateBp: z.number().int(),
  businessDayCutoff: z.string(),
  businessDayAutoClose: z.string().nullable(),
  active: z.boolean(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    setBusinessDay: publicProcedure
      .input(z.object({
      id: z.uuid(),
      businessDayCutoff: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),
      businessDayAutoClose: z
        .string()
        .regex(/^([01]\d|2[0-3]):[0-5]\d$/)
        .optional(),
    }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.enum(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
  pbjtLabel: z.string(),
  pbjtRateBp: z.number().int(),
  pbjtInclusive: z.boolean(),
  serviceName: z.string(),
  serviceRateBp: z.number().int(),
  servicePbjtTaxable: z.boolean(),
  serviceOrderTypes: z.array(z.enum(['dine_in', 'takeaway', 'delivery'])),
  npwp: z.string().nullable(),
  npwpd: z.string().nullable(),
  ppnInclusive: z.boolean(),
  ppnRateBp: z.number().int(),
  businessDayCutoff: z.string(),
  businessDayAutoClose: z.string().nullable(),
  active: z.boolean(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    setActive: publicProcedure
      .input(z.object({ id: z.uuid(), active: z.boolean() }))
      .output(z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  address: z.string().nullable(),
  phone: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.enum(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
  pbjtLabel: z.string(),
  pbjtRateBp: z.number().int(),
  pbjtInclusive: z.boolean(),
  serviceName: z.string(),
  serviceRateBp: z.number().int(),
  servicePbjtTaxable: z.boolean(),
  serviceOrderTypes: z.array(z.enum(['dine_in', 'takeaway', 'delivery'])),
  npwp: z.string().nullable(),
  npwpd: z.string().nullable(),
  ppnInclusive: z.boolean(),
  ppnRateBp: z.number().int(),
  businessDayCutoff: z.string(),
  businessDayAutoClose: z.string().nullable(),
  active: z.boolean(),
}))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    staff: publicProcedure
      .input(z.object({ outletId: z.uuid() }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  roleId: z.string(),
  roleName: z.string(),
  global: z.boolean(),
  approvalBlockedUntil: z.string().nullable(),
})))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    roles: publicProcedure
      .output(z.array(z.object({ id: z.string(), name: z.string() })))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    setStaff: publicProcedure
      .input(z.object({
      outletId: z.uuid(),
      staff: z.array(z.object({ userId: z.uuid(), roleId: z.uuid() })).max(200),
    }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  roleId: z.string(),
  roleName: z.string(),
  global: z.boolean(),
  approvalBlockedUntil: z.string().nullable(),
})))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findUsers: publicProcedure
      .input(z.object({ outletId: z.uuid(), username: z.string().trim().min(1).max(32) }))
      .output(z.array(z.object({ id: z.string(), name: z.string(), username: z.string() })))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    addStaff: publicProcedure
      .input(z.object({
      outletId: z.uuid(),
      name: z.string().trim().min(2).max(80),
      username: z.string().trim().min(3).max(32),
      password: z.string().min(8).max(128),
      pin: z
        .string()
        .regex(/^\d{6}$/)
        .optional(),
      roleId: z.uuid(),
    }))
      .output(z.array(z.object({
  id: z.string(),
  name: z.string(),
  username: z.string(),
  roleId: z.string(),
  roleName: z.string(),
  global: z.boolean(),
  approvalBlockedUntil: z.string().nullable(),
})))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  role: t.router({
    matrix: publicProcedure
      .output(z.object({
      roles: z.array(
        z.object({
          id: z.string(),
          name: z.string(),
          description: z.string().nullable(),
          isGlobal: z.boolean(),
          editable: z.boolean(),
          permissionCount: z.number(),
        }),
      ),
      groups: z.array(
        z.object({
          domain: z.string(),
          rows: z.array(
            z.object({
              key: z.string(),
              description: z.string().nullable(),
              granted: z.array(z.boolean()),
            }),
          ),
        }),
      ),
    }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(z.object({
      name: z.string().trim().min(1).max(40),
      description: z.string().trim().max(200).nullable(),
      permissions: z.array(z.string().max(60)).max(200),
    }))
      .output(z.object({ id: z.string() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      id: z.uuid(),
      name: z.string().trim().min(1).max(40),
      description: z.string().trim().max(200).nullable(),
      permissions: z.array(z.string().max(60)).max(200),
    }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure
      .input(z.object({ id: z.uuid() }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    userPermissions: publicProcedure
      .input(z.object({ userId: z.uuid(), outletId: z.uuid() }))
      .output(z.array(
      z.object({
        permission: z.string(),
        fromRole: z.boolean(),
        override: z.enum(['grant', 'revoke']).nullable(),
        effective: z.boolean(),
      }),
    ))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    setOverride: publicProcedure
      .input(z.object({
      userId: z.uuid(),
      outletIds: z.array(z.uuid()).min(1).max(50),
      permission: z.string().max(60),
      effect: z.enum(['grant', 'revoke']).nullable(),
    }))
      .output(z.object({ success: z.boolean() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  settings: t.router({
    get: publicProcedure
      .output(z.object({ idleTimeoutSeconds: z.number(), desktopLockSeconds: z.number().int() }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(z.object({
      idleTimeoutSeconds: z.number().int().min(30).max(3600).optional(),
      desktopLockSeconds: z.number().int().min(0).max(3600).optional(),
    }))
      .output(z.object({ idleTimeoutSeconds: z.number(), desktopLockSeconds: z.number().int() }))
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  sync: t.router({
    pendingCount: publicProcedure
      .output(z.number().int())
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
