CREATE TABLE "events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"outlet_id" uuid NOT NULL,
	"device_id" text,
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "events_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"type" text NOT NULL,
	"entity_id" uuid NOT NULL,
	"payload" jsonb NOT NULL,
	"actor_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"synced_at" timestamp with time zone,
	CONSTRAINT "events_type_format" CHECK ("events"."type" ~ '^[a-z_]+\.[a-z_]+$')
);
--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_outlet_id_outlets_id_fk" FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "events_outlet_seq_uq" ON "events" USING btree ("outlet_id","seq");--> statement-breakpoint
CREATE INDEX "events_pending_idx" ON "events" USING btree ("outlet_id","seq") WHERE "events"."synced_at" IS NULL;